version: "2"
checks:
  method-complexity:
    enabled: false
  nested-control-flow:
    config:
      threshold: 6
plugins:
  duplication:
    enabled: false
  sonar-python:
    enabled: true
    checks:
      python:S1542:
        enabled: false
      python:S3776:
        enabled: false #TODO: Complexity to 20
  pylint:
    channel: beta
    plugins:
      - django
    checks:
      missing-module-docstring:
        enabled: false
      missing-function-docstring:
        enabled: false
      missing-class-docstring:
        enabled: false
      multiple-imports:
        enabled: false
      import-outside-toplevel:
        enabled: false
      import-error:
        enabled: false
      ungrouped-imports:
        enabled: false
      unnecessary-comprehension:
        enabled: false
      broad-except:
        enabled: false
      no-member:
        enabled: false
      invalid-name:
        enabled: false
  fixme:
    config:
      strings:
        - TOFIX
        - TODO
  csslint:
    enabled: false

exclude_patterns:
  - "src/test.py"