name: Docker Image CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: themaux/chartboard # Nom d'utilisateur Docker Hub (stocké dans les secrets GitHub)
        password: ${{ secrets.DOCKER_PASSWORD }}  # Mot de passe Docker Hub (stocké dans les secrets GitHub)

    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/$APP_NAME:latest .

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/APP_NAMEp:latest
